version: '2.2'
services:
  instruction:
    image: alliages/angara-instruction:latest
    container_name: instruction_container
    restart: unless-stopped
    build:
      context: .
      target: build
    ports:
      - 8081:8080
    env_file:
      - .env_ms_instruction
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    #command: node ace serve --watch
    networks:
      - app-network
    depends_on:
      - mysql


  mysql:
    image: mysql:8.0.40
    container_name: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: 'haisen'
      MYSQL_PASSWORD: 'youcan'
      MYSQL_DATABASE: 'angara_db'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'secret'

    expose:
      - 3307
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
